Update links.yml
Signed-off-by: Glenn Jocher <glenn.jocher@ultralytics.com>

diff --git a/.github/workflows/links.yml b/.github/workflows/links.yml
--- a/.github/workflows/links.yml
+++ b/.github/workflows/links.yml
@@ -3,6 +3,7 @@
 # Continuous Integration (CI) GitHub Actions tests broken link checker using https://github.com/lycheeverse/lychee
 # Ignores the following status codes to reduce false positives:
 #   - 401(Vimeo, 'unauthorized')
+
 #   - 403(OpenVINO, 'forbidden')
 #   - 429(Instagram, 'too many requests')
 #   - 500(Zenodo, 'cached')
@@ -86,7 +87,7 @@ jobs:
 
       - name: Run codespell on downloaded pages
         id: codespell
-        continue-on-error: true
+        continue-on-error: true  # Ensure the workflow continues even if spelling errors are found
         run: |
           # Run codespell and capture output
           pip install codespell
@@ -117,6 +118,9 @@ jobs:
             # Set output for Slack notification
             echo "CODESPELL_ERRORS=$ESCAPED_ERROR_DETAILS_EMOJI" >> $GITHUB_OUTPUT
             echo "CODESPELL_FAILED=true" >> $GITHUB_OUTPUT
+
+            # Exit with a non-zero code to indicate that spelling errors were found
+            exit 123
           else
             echo "No spelling errors found ✅"
             echo "CODESPELL_FAILED=false" >> $GITHUB_OUTPUT
@@ -125,6 +129,7 @@ jobs:
       - name: Run Broken Link Checks on Website
         id: lychee
         uses: ultralytics/actions/retry@main
+        if: false
         with:
           timeout_minutes: 60
           retry_delay_seconds: 900
